export const metadata = {
  title: "Venturex Dao | Explore Investments",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <main className="my-[8rem]">{children}</main>;
}
