import Footer from "../../components/footer/Footer";
import Header from "../../components/header/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import localFont from "next/font/local";

const body = localFont({
  src: "../../public/fonts/neue/NeueMontreal-Book.otf",
});

const heading = localFont({
  src: "../../public/fonts/agrandir/Heavy.otf",
  variable: "--heading",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${body.className} ${heading.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
