import Footer from "../../components/footer/Footer";
import Header from "../../components/header/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import localFont from "next/font/local";

const body = localFont({
  src: "../../public/fonts/neue/NeueMontreal-Book.otf",
});

const heading = localFont({
  src: "../../public/fonts/agrandir/Heavy.otf",
  variable: "--heading",
});

const headTwo = localFont({
  src: "../../public/fonts/agrandir/Bold.otf",
  variable: "--heading-two",
});

const neue = localFont({
  src: "../../public/fonts/agrandir/Bold.otf",
  variable: "--neue",
});

export const metadata = {
  title: "Venturex Dao | Welcome",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${body.className} ${heading.variable} ${headTwo.variable} ${neue.variable} overflow-x-hidden`}
      >
        {/* <Header /> */}
        {children}

        <Footer />
      </body>
    </html>
  );
}
